version: '3'

services:
  database:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "5433:5432"
    environment:
      MYSQL_DATABASE: carbrands
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
