version: '3.9'

services:
  database:
    image: mysql:8
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 333666
        MYSQL_DATABASE: carbrands
        MYSQL_USER: root
        MYSQL_PASSWORD: 333666
volumes:
  db_data:
